#!/bin/bash

items=()

if [ -d "scriptlets" ]; then
    cd $(pwd)
else
    cd "$HOME/LinuxPatcher"
    if [ -d "scriptlets" ]; then
        cd $(pwd)
    else
        cd "$HOME/.techguy16/LinuxPatcher"
    fi
fi
WORKDIR=$(pwd)



parse() {
    cd "$2"
    while read item; do
        item_sel=$(echo "$item" | awk -F"|" '{print $2}')
        chmod +x "./scriptlets/${item_sel}.sh"
        bash "./scriptlets/${item_sel}.sh"
    done <<< "$1"
}

main() {
    content=$(ls scriptlets)
    while read item; do
        items+=("FALSE" "$(echo $item | sed 's/.sh//g')")
    done <<< "$content" #scriptlets/list

    selection=$(yad --title="LinuxPatcher" --list --text="Run the following useful scripts to fix annoying problems in programs" \
        --column="Select" --column="Name" --checklist  "${items[@]}" --width=400 --height=600 --center \
        --icon-size="48" --image="computer" --keep-icon-size --image-on-top --compact)

    if [[ ! -n "$selection" ]]; then
        exit 0
    else 
        pkexec ./gui parse "$(printf "%s|" "$selection")" "$WORKDIR"
    fi
}

if [[ "$1" == "parse" ]]; then
    parse "$2" "$3"
else
    main
fi